### ISSUE TITLE
Обновите пожалуйста модуль

### ISSUE THREAD

**Issue by EightShift** [PayBox/module-joomla-JoomShopping#1]
Обновите пожалуйста модуль, не работает в новых версиях джумлы и джумшоппинга.

**Comment by PayBoxKAZ** [comment]
Обновление данного модуля, а так же разработка модулей под другие cms выполняются в порядке очереди в штатном режиме.

**Comment by EightShift** [comment]
Не согласен.
Все модули были обновлены сравнительно недавно, кроме JoomShopping, которому уже больше трех лет. Он не работает на новых версиях Joomla.
Разве Вас не беспокоит наличие большого количества дыр в безопасности старой версии CMS?
